# token to connect your telegram bot
bot_token: <bot_token>
# connection to database
db_connect_link: postgresql://<user>:<pass>!@<ip>:<port>/<db_name>
# url to scrap images from, only lamodaru supported with exactly 60 products on 1 page
url_to_scrap: https://www.lamoda.ru/c/5971/shoes-muzhkrossovki
# path to chrome driver
chrome_driver_path: C:/Users/user/Desktop/chromedriver-win64
# number of pages to scrape
num_of_pages_to_scrap: 20
# sql table name where to save scraped data
table_name: main_table
# scrolling pause while scraping
scroll_pause_time: 0.2
# sql info
user: <user>
password: <pass>
host: <ip>
port: <port>
database: <db_name>
