# token to connect your telegram bot
bot_token: <bot token>
# connection to database
db_connect_link: postgresql://<user>:<password>@<ip>:<port>/<database_name>
# url to scrap images from, only lamodaru supported with exactly 60 products on 1 page
# example: https://www.lamoda.ru/c/5971/shoes-muzhkrossovki +- /?sort=new
url_to_scrap: <url> #/?sort=new
# path to chrome driver
# ./chromedriver for Docker
chrome_driver_path: <path_to_chrome_driver>
# number of pages to scrape
num_of_pages_to_scrap: 20
# sql table name where to scrape data
table_name: <table name>
# scrolling pause while scraping
scroll_pause_time: 0.2
# sql info
user: <user>
password: <password>
host: <ip>
port: <port>
database: <database_name>